// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1QSJ5T4klP_V8F4BEvfjxyRqsKG4d98',
    appId: '1:262890812424:web:f90acf8bea84eb2c91cdbd',
    messagingSenderId: '262890812424',
    projectId: 'easylister-9f867',
    authDomain: 'easylister-9f867.firebaseapp.com',
    storageBucket: 'easylister-9f867.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmvbd8QMv3vK3UW_KpBzTKlpyazkBgYQ',
    appId: '1:262890812424:android:2f87b4c91b5e96f291cdbd',
    messagingSenderId: '262890812424',
    projectId: 'easylister-9f867',
    storageBucket: 'easylister-9f867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9d63OSKeBO-1s4sDaKXzlu1E1Lt2x1mk',
    appId: '1:262890812424:ios:22aae78fae580c0e91cdbd',
    messagingSenderId: '262890812424',
    projectId: 'easylister-9f867',
    storageBucket: 'easylister-9f867.firebasestorage.app',
    iosBundleId: 'com.example.easyList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9d63OSKeBO-1s4sDaKXzlu1E1Lt2x1mk',
    appId: '1:262890812424:ios:22aae78fae580c0e91cdbd',
    messagingSenderId: '262890812424',
    projectId: 'easylister-9f867',
    storageBucket: 'easylister-9f867.firebasestorage.app',
    iosBundleId: 'com.example.easyList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA1QSJ5T4klP_V8F4BEvfjxyRqsKG4d98',
    appId: '1:262890812424:web:095ca469762b412291cdbd',
    messagingSenderId: '262890812424',
    projectId: 'easylister-9f867',
    authDomain: 'easylister-9f867.firebaseapp.com',
    storageBucket: 'easylister-9f867.firebasestorage.app',
  );
}
