// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLD4vmJLTdZ319AMt9aHiLoAp1PbTJGC0',
    appId: '1:782541960078:web:57d177a1c98b192575eadf',
    messagingSenderId: '782541960078',
    projectId: 'csen268-group6',
    authDomain: 'csen268-group6.firebaseapp.com',
    storageBucket: 'csen268-group6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgk4m_k3Epbf1NPLZjmrafZpBDR7Bg6nQ',
    appId: '1:782541960078:android:4b1c5feed6ff81ec75eadf',
    messagingSenderId: '782541960078',
    projectId: 'csen268-group6',
    storageBucket: 'csen268-group6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxhcjyxbVl6TEuvtidNRgv7IZSwTFs60',
    appId: '1:782541960078:ios:dc49d99a2d5db31775eadf',
    messagingSenderId: '782541960078',
    projectId: 'csen268-group6',
    storageBucket: 'csen268-group6.firebasestorage.app',
    iosBundleId: 'com.example.easyList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfxhcjyxbVl6TEuvtidNRgv7IZSwTFs60',
    appId: '1:782541960078:ios:dc49d99a2d5db31775eadf',
    messagingSenderId: '782541960078',
    projectId: 'csen268-group6',
    storageBucket: 'csen268-group6.firebasestorage.app',
    iosBundleId: 'com.example.easyList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLD4vmJLTdZ319AMt9aHiLoAp1PbTJGC0',
    appId: '1:782541960078:web:0e39684ef4cc9c1b75eadf',
    messagingSenderId: '782541960078',
    projectId: 'csen268-group6',
    authDomain: 'csen268-group6.firebaseapp.com',
    storageBucket: 'csen268-group6.firebasestorage.app',
  );

}